---
#need update & upgrade tasks

- name: install web-server Apache, python & pip3
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - python3
    - python3-pip
