---

- name: Preparing remote server for deploying
  hosts: ubuntu_servers
  tasks:
  - name: Updating ansible repositories
    ansible.builtin.apt:
      update_cache: yes 
  - name: Upgrade system
    ansible.builtin.apt:
      upgrade: yes

- name: install web-server Apache, python & pip3
  hosts: ubuntu_servers
  tasks:
  - name: Install Apache
    ansible.builtin.apt:
      name: apache2
      state: present
  - name: Install wsgi module for Apache
    ansible.builtin.apt:
      name: libapache2-mod-wsgi-py3
      state: present
  - name: Install python3
    ansible.builtin.apt:
      name: python3
      state: present
  - name: Install pip3
    ansible.builtin.apt:
      name: python3-pip
      state: present

- name: move application to the server and install requirements
  hosts: ubuntu_servers
  tasks:
  - name: Copying application to remote server
    ansible.builtin.copy:
      src: ./flask_app
      dest: /var/www/
      owner: root
      group: root
      mode: 0755
  - name: install python packages from requirements.txt
    ansible.builtin.pip:
      requirements: /var/www/flask_app/requirements.txt

- name: configure apache server
  hosts: ubuntu_servers
  tasks:
  - name: Copying flask site config for apache
    ansible.builtin.copy:
      src: ./flask_application.conf
      dest: /etc/apache2/sites-available/
      owner: root
      group: root
      mode: 0644
  - name: check if wsgi-mod for apache is enabled
    community.general.apache2_module:
      name: wsgi
      state: present
  - name: disable 000-default site and enable flask_application site for apache
    ansible.builtin.shell:
      cmd: a2dissite 000-default.conf && a2ensite flask_application.conf
  - name: reload configuration 
    ansible.builtin.systemd:
      name: apache2
      state: reloaded

